### ISSUE TITLE
Error when compile the transform_image.cpp : : ‘t1_p’ does not name a type

### ISSUE THREAD

**Issue by ZheC** [eldar/deepcut-cnn#1]
Did you meet similar error before?

src/caffe/pose/transform_image.cpp:163:5: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
     auto t1_p = pad_to_3x3(t1);
     ^
src/caffe/pose/transform_image.cpp:163:10: error: ‘t1_p’ does not name a type
     auto t1_p = pad_to_3x3(t1);
          ^
src/caffe/pose/transform_image.cpp:164:5: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
     auto t2_p = pad_to_3x3(t2);
     ^
src/caffe/pose/transform_image.cpp:164:10: error: ‘t2_p’ does not name a type
     auto t2_p = pad_to_3x3(t2);
          ^
src/caffe/pose/transform_image.cpp:165:19: error: ‘t1_p’ was not declared in this scope
     cv::Mat res = t1_p \* t2_p;

**Comment by eldar** [comment]
You should build it with C++ 11 support enabled. Add CXXFLAGS += -std=c++11 to your Makefile.config.

**Comment by ZheC** [comment]
Thanks, compiling problem solved. By the way, I tried your another code: https://github.com/eldar/deepcut. The demo_multiperson takes about 4 minutes to get the result for one image. How could I make the code in testing mode (not in demo mode) and make it slightly quicker?

**Comment by leonid-pishchulin** [comment]
you should open the issues related to the multi-person pose estimation in the corresponding git repo. This is true, though, that current implementation runs on the order of several minutes on crowded images containing multiple overlapping people. Please refer to http://pose.mpi-inf.mpg.de/contents/insafutdinov16arxiv.pdf for run-time analysis. We will be working on exploring the ways of reducing run-time.

**Comment by ZheC** [comment]
Thanks for the explanation, the pose estimation results look impressive. I agree that I should report the issue in the other repo, sorry about that.
