### ISSUE TITLE
confusing mix of Makefile.config.example and cmake

### ISSUE THREAD

**Issue by TheTesla** [eldar/deepcut-cnn#4]
It seams to be, that the project can be compiled in two different ways: by starting make in the project root or to use cmake (better in build directory). This may result in inconsistence. What is the better way to compile it?

**Comment by eldar** [comment]
We build on top of Caffe, and the build system is inherited. I personally build it with Makefile.config, but you can do it however you want, for that consult Caffe documentation. Therefore closing this one.
