### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by gjtjx** [eldar/deepcut-cnn#6]
can you send the train code?thank you

**Comment by eldar** [comment]
Hi, I haven't released the training procedure, though the code is there. I plan to release the complete training code within next month. However you can already train it with the existing code, you just have to prepare the data yourself. Here are the instructions:

> For pre-processing, the crucial part is the scaling of input images:
> persons have to have reference height of 400px.
> 
> We scale training images by scale = refHeight/(8*headSize)
> refHeight is in your case 400. headSize is computed by the following
> function:
> 
> function headSize = util_get_head_size(rect)
> 
> SC_BIAS = 0.6;
> headSize = SC_BIAS*norm([rect.x2 rect.y2] - [rect.x1 rect.y1]);
> 
> In this case rect is a a rectangle around person's head.
> This will result in a more or less optimal scale for our model.
> At training time it also does +- 15% scale augmentation, so there is some
> invariance as well.
> You can also do +- 30% scale jitter.
> 
> I attached the files necessary for training (train prototxt for
> resnet-101), train_data.txt is the description of training
> data, format is pretty easy:
> 
> # 0 <- zero-indexed image id, sequential
> /home/andriluk/IMAGES/human_pose_dataset/dataset/dataset_release_candidate1//train-v15/singlePerson/h400-deltaCrop-130-130-bCropIsolated/im00005_1.png
> <- image
> 3 <- number of channels, always 3
> 391 <- image height
> 302 <- image width
> 14 <- number of keypoints present in the image
> 1 175 261 <- 1-indexed keypoint id, x, y in pixel coordinates
> 2 173 178
> 3 144 122
> 4 193 124
> 5 203 146
> 6 200 153
> 7 166 144
> 8 131 107
> 9 163 111
> 10 223 122
> 11 224 159
> 12 220 207
> 13 199 126
> 14 220 82
> 
> I use SGD for training, pretrain it at LR=0.001, then raise it for 0.002
> train for ~400k iters, then drop to 0.002 for 300k and then to 0.001 for
> another 300k, you don't have to do it exactly the same, you can play with
> it.

I attached files with training model definitions, example of a file with the training set and script how to run it. Hope it helps.

[deepercut.zip](https://github.com/eldar/deepcut-cnn/files/551001/deepercut.zip)

**Comment by tiepnh** [comment]
@eldar : I am trying to re-proceduce your work.
But in file pose_data_layer.cpp, I saw that there is hard code for 'joints_stats_file'
```
  auto joint_stats_file = this->layer_param().pose_data_param().has_joint_pairs_stats() ?
              this->layer_param().pose_data_param().joint_pairs_stats() :
              "/BS/eldar/work/pose/exp/mpii-all-joints-reg/data/all_stats.txt";
```
Could you tell me, what is the meaning of file 'all_stats.txt' and how to get it.
Thank in advance

**Comment by mindcont** [comment]
@tiepnh 
Have you solved this problems? I also want to re-proceduce this amazing work!

**Comment by tiepnh** [comment]
@mindcont : sorry, not yet. I still wait for @eldar 's answer. I'm trying read the code, but still cannot figure out that the all_stats.txt means

**Comment by mindcont** [comment]
Thank you for your reply, I am also working on it , any progress I will let you konw
> @mindcont : sorry, not yet. I still wait for @eldar 's answer. I'm trying read the code, but still cannot figure out that the all_stats.txt means

**Comment by tiepnh** [comment]
Hi @mindcont , do you have any update from this work ??
I tried to train the new network by remove joint_stats_file and also remove "regression to other part" in network.  And it worked. But, there is no additional regression step

**Comment by mindcont** [comment]
Hi @tiepnh 
Thanks for your notify,sorry to reply to you so late, I also working on combine network,get some inspire from 

|--|--|
|--|--|
|deepcut|https://github.com/eldar/deepcut |
|cpm|https://github.com/shihenw/convolutional-pose-machines-release |
|personalized_pose|https://github.com/jjcharles/personalized_pose |
|pose-hg-demo|https://github.com/anewell/pose-hg-demo |

etc.Until now did not get good results :bowtie:

**Comment by eldar** [comment]
Hey,

I've re-implemented this ConvNet in TensorFlow, here's the code: https://github.com/eldar/pose-tensorflow. It is more hacker-friendly and I added some training instructions. Sorry, that it took me a while :)

Cheers,
Eldar.
